### ISSUE TITLE
Aktiv, Historik, Tilbud, Check Ind navbar for users

### ISSUE THREAD

**Issue by Pewtro** [Studiegruppe/GarderobeApp#9]
Toppen af dette screenshot - skal vises på specifik del af bottom navbar. 
Kræver #2 

![image](https://user-images.githubusercontent.com/29204244/48058023-bd88f600-e1b5-11e8-9900-967b1ce07d39.png)

**Comment by DanielSdahl** [comment]
https://www.npmjs.com/package/react-native-underline-tabbar
